Presentation/KocSistem.CommunityEdition.Mvc/src/Models/EmailTemplate/ApiEmailTemplateGetResponseModel.cs
// <copyright file="ApiEmailTemplateGetResponseModel.cs" company="KocSistem">
// Copyright (c) KocSistem. All rights reserved.
// Licensed under the Proprietary license. See LICENSE file in the project root for full license information.
// </copyright>

namespace KocSistem.CommunityEdition.Mvc.Models.EmailTemplate
{
    public class ApiEmailTemplateGetResponseModel
    {
        public Guid Id { get; set; }

        public string Name { get; set; }

        public DateTime? UpdatedDate { get; set; }

        public string SupportedLanguages { get; set; }
    }
}

Presentation/KocSistem.CommunityEdition.Mvc/src/Models/EmailTemplate/EmailTemplatePutModel.cs
// <copyright file="EmailTemplatePutModel.cs" company="KocSistem">
// Copyright (c) KocSistem. All rights reserved.
// Licensed under the Proprietary license. See LICENSE file in the project root for full license information.
// </copyright>

namespace KocSistem.CommunityEdition.Mvc.Models.EmailTemplate
{
    public class EmailTemplatePutModel
    {
        public Guid Id { get; set; }

        public string To { get; set; }

        public string Cc { get; set; }

        public string Bcc { get; set; }

        public List<EmailTemplateTranslationsModel> Translations { get; set; }
    }
}

Presentation/KocSistem.CommunityEdition.Mvc/src/Models/EmailTemplate/EmailTemplatePutViewModel.cs
// <copyright file="EmailTemplatePutViewModel.cs" company="KocSistem">
// Copyright (c) KocSistem. All rights reserved.
// Licensed under the Proprietary license. See LICENSE file in the project root for full license information.
// </copyright>

namespace KocSistem.CommunityEdition.Mvc.Models.EmailTemplate
{
    public class EmailTemplatePutViewModel
    {
        public Guid Id { get; set; }

        public string To { get; set; }

        public string Cc { get; set; }

        public string Bcc { get; set; }

        public List<EmailTemplateTranslationsModel> Translations { get; set; }
    }
}

Presentation/KocSistem.CommunityEdition.Mvc/src/Models/EmailTemplate/EmailTemplateSearchRequest.cs
// <copyright file="EmailTemplateSearchRequest.cs" company="KocSistem">
// Copyright (c) KocSistem. All rights reserved.
// Licensed under the Proprietary license. See LICENSE file in the project root for full license information.
// </copyright>

using KocSistem.CommunityEdition.Mvc.Models.Paging;

namespace KocSistem.CommunityEdition.Mvc.Models.EmailTemplate
{
    public class EmailTemplateSearchRequest : PagedRequest
    {
        public string Name { get; set; }
    }
}

Presentation/KocSistem.CommunityEdition.Mvc/src/Models/EmailTemplate/EmailTemplateTranslationsModel.cs
// <copyright file="EmailTemplateTranslationsModel.cs" company="KocSistem">
// Copyright (c) KocSistem. All rights reserved.
// Licensed under the Proprietary license. See LICENSE file in the project root for full license information.
// </copyright>

using KocSistem.CommunityEdition.Common.Enums;
using System.ComponentModel.DataAnnotations;

namespace KocSistem.CommunityEdition.Mvc.Models.EmailTemplate
{
    public class EmailTemplateTranslationsModel
    {
        [Required]
        [Display(Name = "Subject")]
        [StringLength(500, ErrorMessage = "SubjectValidationError")]
        public string Subject { get; set; }

        [Required]
        [Display(Name = "EmailContent")]
        public string EmailContent { get; set; }

        [Required]
        public LanguageType Language { get; set; }
    }
}

Presentation/KocSistem.CommunityEdition.Mvc/src/Models/EmailTemplate/EmailTemplateViewModel.cs
// <copyright file="EmailTemplateViewModel.cs" company="KocSistem">
// Copyright (c) KocSistem. All rights reserved.
// Licensed under the Proprietary license. See LICENSE file in the project root for full license information.
// </copyright>

using System.ComponentModel.DataAnnotations;

namespace KocSistem.CommunityEdition.Mvc.Models.EmailTemplate
{
    public class EmailTemplateViewModel
    {
        public EmailTemplateViewModel()
        {
            this.Translations = new List<EmailTemplateTranslationsModel>();
        }

        [Display(Name = "Id")]
        public Guid Id { get; set; }

        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "To")]
        public string To { get; set; }

        [Display(Name = "Cc")]
        public string Cc { get; set; }

        [Display(Name = "Bcc")]
        public string Bcc { get; set; }

        [Display(Name = "UpdatedUser")]
        public string UpdatedUser { get; set; }

        [Display(Name = "UpdatedDate")]
        public DateTime? UpdatedDate { get; set; }

        public List<EmailTemplateTranslationsModel> Translations { get; set; }
    }
}

Presentation/KocSistem.CommunityEdition.Mvc/src/Models/EmailTemplate/SendTryMailModel.cs
// <copyright file="SendTryMailModel.cs" company="KocSistem">
// Copyright (c) KocSistem. All rights reserved.
// Licensed under the Proprietary license. See LICENSE file in the project root for full license information.
// </copyright>

namespace KocSistem.CommunityEdition.Mvc.Models.EmailTemplate
{
    public class SendTryMailModel
    {
        public string To { get; set; }

        public string Subject { get; set; }

        public string Content { get; set; }
    }
}

Presentation/KocSistem.CommunityEdition.Mvc/src/Controllers/EmailTemplateController.cs
// <copyright file="EmailTemplateController.cs" company="KocSistem">
// Copyright (c) KocSistem. All rights reserved.
// Licensed under the Proprietary license. See LICENSE file in the project root for full license information.
// </copyright>

using KocSistem.CommunityEdition.Common.Authentication;
using KocSistem.CommunityEdition.Mvc.Helpers;
using KocSistem.CommunityEdition.Mvc.Models.DataTables;
using KocSistem.CommunityEdition.Mvc.Models.EmailTemplate;
using KocSistem.CommunityEdition.Mvc.Models.Paging;
using KocSistem.OneFrame.DesignObjects.Services;
using Microsoft.AspNetCore.Authorization;

namespace KocSistem.CommunityEdition.Mvc.Controllers
{
    [Route("email-templates")]
    public class EmailTemplateController : BaseController<EmailTemplateController>
    {
        private readonly IKsStringLocalizer<EmailTemplateController> _ksStringLocalizer;

        public EmailTemplateController(IKsI18N i18N)
             : base(i18N)
        {
            _ksStringLocalizer = i18N.GetLocalizer<EmailTemplateController>();
        }

        [HttpGet]
        [Authorize(Policy = KsPermissionPolicy.ManagementEmailTemplateList)]
        public IActionResult Get()
        {
            return View();
        }

        [HttpGet("{id}", Name = "GetEmailTemplateInfo")]
        [Authorize(Policy = KsPermissionPolicy.ManagementEmailTemplateList)]
        public async Task<IActionResult> GetEmailTemplateInfoAsync(Guid id)
        {
            var response = await GetApiRequestAsync<ServiceResponse<EmailTemplateViewModel>>(string.Format(ApiEndpoints.EmailTemplateById, id)).ConfigureAwait(false);

            if (!response.IsSuccessful)
            {
                return ToastError(response.Error);
            }

            return View(response.Result);
        }

        [HttpGet("list")]
        [Authorize(Policy = KsPermissionPolicy.ManagementEmailTemplateList)]
        public async Task<IActionResult> GetListAsync([DataTablesRequest] DataTablesRequest request)
        {
            var pagedRequest = GetPagedRequest(request);

            if (!string.IsNullOrEmpty(request.Search?.Value))
            {
                var emailTemplateSearchRequest = GetEmailTemplateSearchRequest(request);
                return await SearchAsync(emailTemplateSearchRequest).ConfigureAwait(false);
            }

            var response = await GetApiRequestWithCookiesAsync<ServiceResponse<PagedResult<ApiEmailTemplateGetResponseModel>>>(ApiEndpoints.EmailTemplatePagedList, pagedRequest).ConfigureAwait(false);

            if (!response.IsSuccessful)
            {
                return ToastError(response.Error);
            }

            return Ok(JsonDataTable(response.Result));
        }

        [HttpPut]
        [Authorize(Policy = KsPermissionPolicy.ManagementEmailTemplateEdit)]
        public async Task<IActionResult> PutAsync(EmailTemplatePutModel model)
        {
            var response = await PutApiRequestAsync<ServiceResponse>(ApiEndpoints.EmailTemplateBaseRoute, model).ConfigureAwait(false);

            if (!response.IsSuccessful)
            {
                return ToastError(response.Error);
            }

            return ToastSuccessForRedirect(_ksStringLocalizer["UpdateEmailTemplateSuccess"], MvcEndpoints.EmailTemplateBaseRoute);
        }

        [HttpPost("send-email")]
        [Authorize(Policy = KsPermissionPolicy.ManagementEmailTemplateEdit)]
        public async Task<IActionResult> SendEmailAsync(SendTryMailModel model)
        {
            await PostApiRequestAsync<ServiceResponse>(ApiEndpoints.EmailTemplateSendTryMail, model).ConfigureAwait(false);

            return ToastSuccess(_ksStringLocalizer["SendEmailSuccess"]);
        }

        [HttpGet("search")]
        [Authorize(Policy = KsPermissionPolicy.ManagementEmailTemplateList)]
        public async Task<IActionResult> SearchAsync([FromQuery] EmailTemplateSearchRequest searchRequest)
        {
            var response = await GetApiRequestAsync<ServiceResponse<PagedResult<ApiEmailTemplateGetResponseModel>>>(ApiEndpoints.EmailTemplateSearch, searchRequest).ConfigureAwait(false);

            if (!response.IsSuccessful)
            {
                return ToastError(response.Error);
            }

            return Ok(JsonDataTable(response.Result));
        }

        private static EmailTemplateSearchRequest GetEmailTemplateSearchRequest(DataTablesRequest requestModel)
        {
            var emailTemplateSearchRequest = new EmailTemplateSearchRequest()
            {
                Name = requestModel.Search.Value,
                PageIndex = requestModel.Start / requestModel.Length,
                PageSize = requestModel.Length,
            };
            return emailTemplateSearchRequest;
        }
    }
}

Presentation/KocSistem.CommunityEdition.Mvc/src/Views/EmailTemplate/Get.cshtml
@using KocSistem.CommunityEdition.Mvc.Controllers
@using KocSistem.OneFrame.I18N
@inject HtmlRtlSuffixHelper _htmlRtlSuffixHelper
@inject HtmlMinSuffixHelper _htmlMinSuffixHelper
@using KocSistem.CommunityEdition.Mvc.Helpers
@inject IKsStringLocalizer<EmailTemplateController> _localizer
@{
    ViewData["Title"] = _localizer["EmailTemplateList"];
}

@section scripts
{
<script src="~/metronic/assets/plugins/custom/datatables/datatables.bundle.js" type="text/javascript"></script>
<script src="~/js/helpers/datatablehelper@(_htmlMinSuffixHelper.MinSuffix).js" type="text/javascript"></script>
<script src="~/js/emailTemplate/get@(_htmlMinSuffixHelper.MinSuffix).js" type="text/javascript"></script>
}

@section headerBegin
{
<link href="~/metronic/assets/plugins/custom/datatables/datatables.bundle@(_htmlRtlSuffixHelper.RtlFileSuffix).css" rel="stylesheet" type="text/css" />
}

<div class="row">
    <div class="card">
        <div class="card-header border-0 pt-6">
            <div class="card-title">
                <div class="d-flex align-items-center position-relative my-1">
                    <span class="svg-icon svg-icon-1 position-absolute ms-6">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="black" />
                            <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="black" />
                        </svg>
                    </span>
                    <input type="text" class="form-control form-control-solid w-250px ps-15 datatable-search" placeholder='@_localizer["DataTable_search"]' />
                </div>
            </div>
        </div>
        <div class="card-body pt-0">
            <table class="table align-middle table-row-dashed fs-6 gy-5" id="table_emailTemplate">
                <thead>
                    <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                        <th>@_localizer["EmailTemplateName"]</th>
                        <th>@_localizer["UpdatedDate"]</th>
                        <th>@_localizer["SupportedLanguages"]</th>
                        <th></th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

Presentation/KocSistem.CommunityEdition.Mvc/src/Views/EmailTemplate/GetEmailTemplateInfo.cshtml
@using KocSistem.CommunityEdition.Mvc.Controllers
@using KocSistem.CommunityEdition.Mvc.Helpers
@using KocSistem.CommunityEdition.Mvc.Models.EmailTemplate
@using KocSistem.OneFrame.I18N
@using Microsoft.AspNetCore.Builder
@using Microsoft.Extensions.Options
@inject HtmlMinSuffixHelper _htmlMinSuffixHelper
@model KocSistem.CommunityEdition.Mvc.Models.EmailTemplate.EmailTemplateViewModel
@inject IKsStringLocalizer<EmailTemplateController> _localizer
@inject IOptions<RequestLocalizationOptions> _locOptions

@{
    ViewData["Title"] = _localizer["EmailTemplateManagement"];
    var cultureListWithoutDefault = _locOptions.Value.SupportedUICultures.Where(w => w.Name != System.Globalization.CultureInfo.DefaultThreadCurrentCulture.Name).OrderBy(o => o.NativeName).ToList();
    var defaultLanguageIsoTwoLetterName = System.Globalization.CultureInfo.DefaultThreadCurrentCulture.TwoLetterISOLanguageName;
}

@section scripts
{
<script src="~/metronic/assets/plugins/custom/tinymce/tinymce.bundle.js"></script>
<script id="jsEmailTemplateInfo" data-default-language="@defaultLanguageIsoTwoLetterName" src="~/js/emailTemplate/getemailtemplateinfo@(_htmlMinSuffixHelper.MinSuffix).js"></script>
}

<div class="card">
    <div class="card-body p-lg-17">
        <div class="d-flex flex-column flex-lg-row mb-17">
            <div class="flex-lg-row-fluid">
                <form class="form mb-15" novalidate="novalidate" id="emailTemplateEditForm" asp-controller="EmailTemplate" asp-action="Put" method="PUT">
                    <input asp-for="Id" type="hidden" id="emailTemplateIdHidden" />
                    <div class="d-flex flex-column mb-5 fv-row">
                        <label class="fs-5 fw-bold mb-2">@_localizer["EmailTemplateName"]</label>
                        <input class="form-control form-control-solid" asp-for="Name" autocomplete="off" disabled="disabled" />
                    </div>
                    <div class="row mb-5">
                        <div class="col-md-4 fv-row">
                            <label class="fs-5 fw-bold mb-2">@_localizer["To"]</label>
                            <input class="form-control form-control-solid multipleEmail" asp-for="To" autocomplete="off" />
                        </div>
                        <div class="col-md-4 fv-row">
                            <label class="fs-5 fw-bold mb-2">@_localizer["Cc"]</label>
                            <input class="form-control form-control-solid multipleEmail" asp-for="Cc" autocomplete="off" />
                        </div>
                        <div class="col-md-4 fv-row">
                            <label class="fs-5 fw-bold mb-2">@_localizer["Bcc"]</label>
                            <input class="form-control form-control-solid multipleEmail" asp-for="Bcc" autocomplete="off" />
                        </div>
                    </div>
                    <div class="separator mb-8"></div>
                    <div class="row  rounded shadow-sm p-lg-10">
                        <div class="d-flex flex-column mb-5">
                            <ul class="nav nav-tabs nav-line-tabs mb-5 fs-6">
                                @{
                                    <li class="nav-item">
                                        <a class="nav-link active" data-bs-toggle="tab" href="#supportedUICultures_0">
                                            @(System.Globalization.CultureInfo.DefaultThreadCurrentCulture.NativeName)
                                        </a>
                                    </li>

                                    for (var i = 0; i < cultureListWithoutDefault.Count; i++)
                                    {
                                        var cultureInfo = cultureListWithoutDefault[i];

                                        <li class="nav-item">
                                            <a class="nav-link" data-bs-toggle="tab" href="#supportedUICultures_@(i+1)">
                                                @cultureInfo.NativeName
                                            </a>
                                        </li>
                                    }
                                }
                            </ul>

                            <div class="tab-content" id="translationTab">
                                @{
                                    var language = Enum.Parse<KocSistem.CommunityEdition.Common.Enums.LanguageType>(System.Globalization.CultureInfo.DefaultThreadCurrentCulture.TwoLetterISOLanguageName);
                                    var defaultCultureIndex = Model.Translations.FindIndex(f => f.Language == language);

                                    if (defaultCultureIndex == -1)
                                    {
                                        Model.Translations.Add(new EmailTemplateTranslationsModel { Language = language });
                                        defaultCultureIndex = Model.Translations.FindIndex(f => f.Language == language);
                                    }

                                    <div class="tab-pane fade show active" id="supportedUICultures_0" role="tabpanel">
                                        <input type="hidden" name="Translations[@defaultCultureIndex].Language" value="@((int)language)" />
                                        <div class="fv-row mb-5">
                                            <label asp-for="Translations[defaultCultureIndex].Subject" class="d-flex align-items-center fs-6 fw-bold form-label mb-2 required"></label>
                                            <input asp-for="Translations[defaultCultureIndex].Subject" class="form-control form-control-solid" autocomplete="off" />
                                        </div>
                                        <div class="fv-row mb-5">
                                            <label asp-for="Translations[defaultCultureIndex].EmailContent" class="d-flex align-items-center fs-6 fw-bold form-label mb-2"></label>
                                            <textarea asp-for="Translations[defaultCultureIndex].EmailContent" autocomplete="off" rows="5" class="form-control form-control-solid tox-target editor"></textarea>
                                        </div>
                                    </div>

                                    for (int i = 0; i < cultureListWithoutDefault.Count; i++)
                                    {
                                        language = Enum.Parse<KocSistem.CommunityEdition.Common.Enums.LanguageType>(cultureListWithoutDefault[i].TwoLetterISOLanguageName);
                                        var index = Model.Translations.FindIndex(f => f.Language == language);

                                        if (index == -1)
                                        {
                                            Model.Translations.Add(new EmailTemplateTranslationsModel { Language = language });
                                            index = Model.Translations.FindIndex(f => f.Language == language);
                                        }

                                        <div class="tab-pane fade" id="supportedUICultures_@(i+1)" role="tabpanel">
                                            <input type="hidden" name="Translations[@index].Language" value="@((int)language)" />
                                            <div class="fv-row mb-5">
                                                <label asp-for="Translations[index].Subject" class="d-flex align-items-center fs-6 fw-bold form-label mb-2 required"></label>
                                                <input asp-for="Translations[index].Subject" class="form-control form-control-solid" autocomplete="off" />
                                            </div>
                                            <div class="fv-row mb-5">
                                                <label asp-for="Translations[index].EmailContent" class="d-flex align-items-center fs-6 fw-bold form-label mb-2"></label>
                                                <textarea asp-for="Translations[index].EmailContent" autocomplete="off" rows="5" class="form-control form-control-solid tox-target editor"></textarea>
                                            </div>
                                        </div>
                                    }
                                }
                            </div>
                        </div>
                    </div>
                    <div class="text-center pt-15">
                        <button type="button" class="btn btn-primary" id="emailTemplateSaveButton">
                            <span class="indicator-label">@_localizer["Save"]</span>
                            <span class="indicator-progress">
                                @_localizer["PleaseWait"]...
                                <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
                            </span>
                        </button>
                        <button id="emailTemplateSendEmailButton" class="btn btn-light me-3">@_localizer["SendEmail"]</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>