Presentation/KocSistem.CommunityEdition.Mvc/src/Models/Authentication/AuthenticatorResponseViewModel.cs
// <copyright file="AuthenticatorResponseViewModel.cs" company="KocSistem">
// Copyright (c) KocSistem. All rights reserved.
// Licensed under the Proprietary license. See LICENSE file in the project root for full license information.
// </copyright>

namespace KocSistem.CommunityEdition.Mvc.Models.Authentication
{
    public class AuthenticatorResponseViewModel
    {
        public bool HasAuthenticatorKey { get; set; }

        public string SharedKey { get; set; }

        public bool IsActivated { get; set; }
    }
}

Presentation/KocSistem.CommunityEdition.Mvc/src/Models/Authentication/Login2FAViewModel.cs
// <copyright file="Login2FAViewModel.cs" company="KocSistem">
// Copyright (c) KocSistem. All rights reserved.
// Licensed under the Proprietary license. See LICENSE file in the project root for full license information.
// </copyright>

using KocSistem.CommunityEdition.Common.Enums;
using System.ComponentModel.DataAnnotations;

namespace KocSistem.CommunityEdition.Mvc.Models.Authentication
{
    public class Login2FaViewModel
    {
        [Required]
        public string VerificationCode { get; set; }

        public Login2Fa VerificationType { get; set; }

        public string SharedKey { get; set; }

        public string QrCodeUri { get; set; }

        public bool? HasAuthenticatorKey { get; set; }

        public bool IsActivated { get; set; }

        public int VerificationTime { get; set; }

        public string PhoneNumberMasked { get; set; }
    }
}

Presentation/KocSistem.CommunityEdition.Mvc/src/Controllers/AuthenticationController.cs
// <copyright file="AuthenticationController.cs" company="KocSistem">
// Copyright (c) KocSistem. All rights reserved.
// Licensed under the Proprietary license. See LICENSE file in the project root for full license information.
// </copyright>

using KocSistem.CommunityEdition.Application.Abstractions.Account.Contracts;
using KocSistem.CommunityEdition.Common.Constants;
using KocSistem.CommunityEdition.Common.Enums;
using KocSistem.CommunityEdition.Mvc.Extensions;
using KocSistem.CommunityEdition.Mvc.Helpers;
using KocSistem.CommunityEdition.Mvc.Models.Account;
using KocSistem.CommunityEdition.Mvc.Models.Authentication;
using KocSistem.OneFrame.DesignObjects.Services;
using Microsoft.AspNetCore.Authorization;
using System.Text.Encodings.Web;

namespace KocSistem.CommunityEdition.Mvc.Controllers
{
    [Route("authentications")]
    public class AuthenticationController : BaseController<AuthenticationController>
    {
        private readonly IKsStringLocalizer<AuthenticationController> _localize;
        private readonly IClaimHelper _claimHelper;
        private readonly UrlEncoder _urlEncoder;

        public AuthenticationController(IKsI18N i18N, UrlEncoder urlEncoder, IClaimHelper claimHelper)
            : base(i18N)
        {
            _localize = i18N.GetLocalizer<AuthenticationController>();
            _urlEncoder = urlEncoder;
            _claimHelper = claimHelper;
        }

        [HttpGet("login-2fa")]
        [AllowAnonymous]
        public async Task<IActionResult> Login2FaAsync()
        {
            var dbConfiguration = GetConfigurationsAsync(new List<string>
            {
                ConfigurationConstant.Identity2FaSettingsType,
                ConfigurationConstant.Identity2FaSettingsVerificationTime,
                ConfigurationConstant.Identity2FaSettingsAuthenticatorLinkName,
            }).Result;

            var login = TempData.Get<LoginViewModel>("LoginModel");
            var twoFactorModel = new Login2FaViewModel
            {
                VerificationType = Enum.Parse<Login2Fa>(dbConfiguration.Identity2FaSettingsType),
                VerificationTime = dbConfiguration.Identity2FaSettingsVerificationTime,
            };

            if (twoFactorModel.VerificationType == Common.Enums.Login2Fa.Authenticator)
            {
                var response = (await PostApiRequestWithAllHeadersAsync<ServiceResponse<AuthenticatorResponseViewModel>>(ApiEndpoints.AuthenticationGenerateAuthenticatorSharedKey, login.Email).ConfigureAwait(false)).Result;
                var qrcodeUri = $"otpauth://totp/{_urlEncoder.Encode(dbConfiguration.Identity2FaSettingsAuthenticatorLinkName)}:{_urlEncoder.Encode(login.Email)}?secret={response.SharedKey}&issuer={_urlEncoder.Encode(dbConfiguration.Identity2FaSettingsAuthenticatorLinkName)}";
                twoFactorModel.HasAuthenticatorKey = response.HasAuthenticatorKey;
                twoFactorModel.SharedKey = response.SharedKey;
                twoFactorModel.QrCodeUri = qrcodeUri;
                twoFactorModel.IsActivated = response.IsActivated;
            }
            else
            {
                var model = new TwoFactorVerificationDto { Username = login.Email, VerificationType = twoFactorModel.VerificationType };

                var serviceResponse = await PostApiRequestWithAllHeadersAsync<ServiceResponse<string>>(ApiEndpoints.AuthenticationSendVerificationCode, model).ConfigureAwait(false);
                twoFactorModel.PhoneNumberMasked = serviceResponse?.Result;
            }

            TempData.Put("LoginModel", login);
            return View(twoFactorModel);
        }

        [HttpPost("login-2fa")]
        [AllowAnonymous]
        public async Task<IActionResult> Login2FaAsync(Login2FaViewModel model)
        {
            var login = TempData.Get<LoginViewModel>("LoginModel");

            var dbConfiguration = GetConfigurationsAsync(new List<string>
            {
                ConfigurationConstant.Identity2FaSettingsType,
            }).Result;

            var twoFactorModel = new TwoFactorVerificationDto
            {
                VerificationCode = model.VerificationCode,
                VerificationType = Enum.Parse<Login2Fa>(dbConfiguration.Identity2FaSettingsType),
                Username = login.Email,
            };

            var verificationResponse = await PostApiRequestWithAllHeadersAsync<ServiceResponse>(ApiEndpoints.AuthenticationTwoFactorVerification, twoFactorModel).ConfigureAwait(false);

            if (verificationResponse.IsSuccessful)
            {
                var response = await PostApiRequestWithAllHeadersAsync<ServiceResponse<LoginResponseViewModel>>(ApiEndpoints.AccountLogin, login).ConfigureAwait(false);
                if (!response.IsSuccessful)
                {
                    return ToastError(response.Error);
                }

                await _claimHelper.BuildClaimsAndSignIn(response.Result).ConfigureAwait(false);

                return ToastSuccessForRedirect(_localize["LoginSuccess"], !string.IsNullOrEmpty(login.ReturnUrl) ? login.ReturnUrl : Url.Action("Index", "Home"));
            }
            else
            {
                TempData.Put("LoginModel", login);

                return ToastError(_localize["ValidationError"] + verificationResponse.Error.Message);
            }
        }
    }
}

Presentation/KocSistem.CommunityEdition.Mvc/src/Views/Authentication/Login2FA.cshtml
@using KocSistem.CommunityEdition.Mvc.Controllers
@using KocSistem.CommunityEdition.Mvc.Helpers
@using KocSistem.OneFrame.I18N
@using KocSistem.CommunityEdition.Common.Enums
@inject HtmlMinSuffixHelper _htmlMinSuffixHelper
@model KocSistem.CommunityEdition.Mvc.Models.Authentication.Login2FaViewModel
@inject IKsStringLocalizer<AuthenticationController> _localizer

@{
    Layout = "~/src/Views/Shared/_LoginLayout.cshtml";
    ViewData["Title"] = _localizer["2FA"];
}
<style>
    #qrcode img {
        display: initial !important;
    }
</style>

@section scripts
{
<script src="~/js/authentication/login2FA@(_htmlMinSuffixHelper.MinSuffix).js"></script>

    @if (Model.VerificationType == Login2Fa.Authenticator)
    {
<script src="~/lib/qrcode/qrcode.js"></script>
<script>
    new QRCode(document.getElementById("qrcode"), {
    text: '@Model.QrCodeUri',
    width: 250,
    height: 250,
    correctLevel: QRCode.CorrectLevel.H
    });
</script>
    }
}

<form class="form w-100 mb-10" novalidate="novalidate" id="twoFactorForm" asp-controller="Authentication" asp-action="Login2FA" method="POST">
    <input type="hidden" asp-for="QrCodeUri" />
    <input type="hidden" asp-for="SharedKey" />
    <input type="hidden" asp-for="VerificationType" />
    <input type="hidden" asp-for="VerificationTime" />
    <input type="hidden" asp-for="VerificationCode" />
    <div class="text-center mb-10">
        <h1 class="text-dark mb-3">@_localizer["2FA"]</h1>
        <div class="text-muted fw-bold fs-5 mb-5">@_localizer["VerificationType"] : @Model.VerificationType</div>
        @if (Model.VerificationType == Login2Fa.Sms)
        {
            <div class="text-muted fw-bold fs-5 mb-5">@_localizer["VerificationCodeSent"]</div>
            <div class="fw-bolder text-dark fs-3">@Model.PhoneNumberMasked</div>
        }
    </div>
    @if (Model.VerificationType == Login2Fa.Authenticator)
    {
        <div class="text-center mb-10">
            @if (!Model.IsActivated)
            {
                <div class="row">
                    <div class="col-md-12">
                    <div class="alert alert-success" role="alert">
                        <span class="text-muted fw-bold fs-5 mb-5">@_localizer["AuthenticatorInfoMessage"]</span>
                    </div>
                </div>
            </div>
            }
            <div class="row">
                <div class="col-md-12 text-center">
                    <div id="qrcode"></div>
                </div>
            </div>
        </div>
    }
    <div class="mb-10 px-md-10">
        <div class="fw-bolder text-start text-dark fs-6 mb-1 ms-1">@_localizer["EnterYourVerificationCode"]</div>
        <div id="verificationCode" class="d-flex flex-stack">
            <input type="text" data-inputmask="'mask': '9', 'placeholder': ''" maxlength="1" class="form-control form-control-solid h-60px w-60px fs-2qx text-center border-primary border-hover mx-1 my-2" value="" />
            <input type="text" data-inputmask="'mask': '9', 'placeholder': ''" maxlength="1" class="form-control form-control-solid h-60px w-60px fs-2qx text-center border-primary border-hover mx-1 my-2" value="" />
            <input type="text" data-inputmask="'mask': '9', 'placeholder': ''" maxlength="1" class="form-control form-control-solid h-60px w-60px fs-2qx text-center border-primary border-hover mx-1 my-2" value="" />
            <input type="text" data-inputmask="'mask': '9', 'placeholder': ''" maxlength="1" class="form-control form-control-solid h-60px w-60px fs-2qx text-center border-primary border-hover mx-1 my-2" value="" />
            <input type="text" data-inputmask="'mask': '9', 'placeholder': ''" maxlength="1" class="form-control form-control-solid h-60px w-60px fs-2qx text-center border-primary border-hover mx-1 my-2" value="" />
            <input type="text" data-inputmask="'mask': '9', 'placeholder': ''" maxlength="1" class="form-control form-control-solid h-60px w-60px fs-2qx text-center border-primary border-hover mx-1 my-2" value="" />
        </div>
    </div>
    <div id="divTimer" class="text-center mb-10">
        <span class="text-muted fw-bold fs-5 mb-5">@_localizer["RemainTime"] </span>
        <span class="badge badge-warning"><strong id="remainTime" class="fw-bolder text-dark fs-3"></strong></span>
        <strong class="text-muted fw-bold fs-5 mb-5"> @_localizer["Second"]</strong>
    </div>
    <div class="d-flex flex-center">
        <button type="button" id="twoFactorButton" class="btn btn-lg btn-primary fw-bolder">
            <span class="indicator-label">@_localizer["Submit"]</span>
            <span class="indicator-progress">
                @_localizer["PleaseWait"]...
                <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
            </span>
        </button>
    </div>
    <div class="d-flex flex-center">
        <button type="button" id="resendButton" class="btn btn-light btn-elevate" style="visibility:hidden">@_localizer["Resend"]</button>
    </div>
</form>