Presentation/KocSistem.CommunityEdition.Mvc/src/Models/ApplicationSettingCategory/ApiAppSettingCategoryGetResponseModel.cs
// <copyright file="ApiAppSettingCategoryGetResponseModel.cs" company="KocSistem">
// Copyright (c) KocSistem. All rights reserved.
// Licensed under the Proprietary license. See LICENSE file in the project root for full license information.
// </copyright>

using System.ComponentModel.DataAnnotations;

namespace KocSistem.CommunityEdition.Mvc.Models.ApplicationSettingCategory
{
    public class ApiAppSettingCategoryGetResponseModel
    {
        [Display(Name = "Id")]
        public Guid Id { get; set; }

        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }
    }
}

Presentation/KocSistem.CommunityEdition.Mvc/src/Models/ApplicationSettingCategory/AppSettingCategoryPutViewModel.cs
// <copyright file="AppSettingCategoryPutViewModel.cs" company="KocSistem">
// Copyright (c) KocSistem. All rights reserved.
// Licensed under the Proprietary license. See LICENSE file in the project root for full license information.
// </copyright>

using System.ComponentModel.DataAnnotations;

namespace KocSistem.CommunityEdition.Mvc.Models.ApplicationSettingCategory
{
    public class AppSettingCategoryPutViewModel
    {
        public Guid Id { get; set; }

        [StringLength(500, ErrorMessage = "NameValidationError")]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }
    }
}

Presentation/KocSistem.CommunityEdition.Mvc/src/Models/ApplicationSettingCategory/ApplicationSettingCategoryPostModel.cs
// <copyright file="ApplicationSettingCategoryPostModel.cs" company="KocSistem">
// Copyright (c) KocSistem. All rights reserved.
// Licensed under the Proprietary license. See LICENSE file in the project root for full license information.
// </copyright>

using System.ComponentModel.DataAnnotations;

namespace KocSistem.CommunityEdition.Mvc.Models.ApplicationSettingCategory
{
    public class ApplicationSettingCategoryPostModel
    {
        [StringLength(500, ErrorMessage = "NameValidationError")]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }
    }
}

Presentation/KocSistem.CommunityEdition.Mvc/src/Models/ApplicationSettingCategory/ApplicationSettingCategorySearchRequest.cs
// <copyright file="ApplicationSettingCategorySearchRequest.cs" company="KocSistem">
// Copyright (c) KocSistem. All rights reserved.
// Licensed under the Proprietary license. See LICENSE file in the project root for full license information.
// </copyright>

using KocSistem.CommunityEdition.Mvc.Models.Paging;
using System.ComponentModel.DataAnnotations;

namespace KocSistem.CommunityEdition.Mvc.Models.ApplicationSettingCategory
{
    public class ApplicationSettingCategorySearchRequest : PagedRequest
    {
        [Display(Name = "Name")]
        public string Name { get; set; }
    }
}

Presentation/KocSistem.CommunityEdition.Mvc/src/Models/ApplicationSettingCategory/ApplicationSettingCategoryViewModel.cs
// <copyright file="ApplicationSettingCategoryViewModel.cs" company="KocSistem">
// Copyright (c) KocSistem. All rights reserved.
// Licensed under the Proprietary license. See LICENSE file in the project root for full license information.
// </copyright>

using System.ComponentModel.DataAnnotations;

namespace KocSistem.CommunityEdition.Mvc.Models.ApplicationSettingCategory
{
    public class ApplicationSettingCategoryViewModel
    {
        public Guid Id { get; set; }

        [StringLength(500, ErrorMessage = "NameValidationError")]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }
    }
}

Presentation/KocSistem.CommunityEdition.Mvc/src/Controllers/ApplicationSettingCategoryController.cs
// <copyright file="ApplicationSettingCategoryController.cs" company="KocSistem">
// Copyright (c) KocSistem. All rights reserved.
// Licensed under the Proprietary license. See LICENSE file in the project root for full license information.
// </copyright>

using KocSistem.CommunityEdition.Common.Authentication;
using KocSistem.CommunityEdition.Mvc.Helpers;
using KocSistem.CommunityEdition.Mvc.Models.ApplicationSettingCategory;
using KocSistem.CommunityEdition.Mvc.Models.DataTables;
using KocSistem.CommunityEdition.Mvc.Models.Paging;
using KocSistem.OneFrame.DesignObjects.Services;
using Microsoft.AspNetCore.Authorization;

namespace KocSistem.CommunityEdition.Mvc.Controllers
{
    [Route("application-setting-categories")]
    public class ApplicationSettingCategoryController : BaseController<ApplicationSettingCategoryController>
    {
        private readonly IKsStringLocalizer<ApplicationSettingCategoryController> _localize;

        public ApplicationSettingCategoryController(IKsI18N i18N)
             : base(i18N)
        {
            _localize = i18N.GetLocalizer<ApplicationSettingCategoryController>();
        }

        [HttpGet("create")]
        [Authorize(Policy = KsPermissionPolicy.ManagementApplicationSettingCategoryCreate)]
        public IActionResult Create()
        {
            return View();
        }

        [HttpDelete]
        [Authorize(Policy = KsPermissionPolicy.ManagementApplicationSettingCategoryDelete)]
        public async Task<IActionResult> DeleteAsync(Guid id)
        {
            var response = await DeleteApiRequestAsync<ServiceResponse>(ApiEndpoints.ApplicationSettingCategoryBaseRoute + id).ConfigureAwait(false);

            if (!response.IsSuccessful)
            {
                return ToastError(response.Error);
            }

            return ToastSuccessForRedirect(_localize["DeleteApplicationSettingCategorySuccess"], MvcEndpoints.ApplicationSettingCategoryBaseRoute);
        }

        [HttpGet]
        [Authorize(Policy = KsPermissionPolicy.ManagementApplicationSettingCategoryList)]
        public IActionResult Get()
        {
            return View();
        }

        [HttpGet("{id}")]
        [Authorize(Policy = KsPermissionPolicy.ManagementApplicationSettingCategoryList)]
        public async Task<IActionResult> GetAppSettingCategoryInfoAsync(Guid id)
        {
            var response = await GetApiRequestAsync<ServiceResponse<ApplicationSettingCategoryViewModel>>(string.Format(ApiEndpoints.ApplicationSettingCategoryGetById, id)).ConfigureAwait(false);

            if (!response.IsSuccessful)
            {
                return ToastError(response.Error);
            }

            return PartialView(response.Result);
        }

        [HttpGet("list")]
        [Authorize(Policy = KsPermissionPolicy.ManagementApplicationSettingCategoryList)]
        public async Task<IActionResult> GetListAsync([DataTablesRequest] DataTablesRequest request)
        {
            var pagedRequest = GetPagedRequest(request);

            if (!string.IsNullOrEmpty(request.Search?.Value))
            {
                var applicationSettingCategorySearchRequest = GetApplicationSettingCategorySearchRequest(request);
                return await SearchAsync(applicationSettingCategorySearchRequest).ConfigureAwait(false);
            }

            var response = await GetApiRequestAsync<ServiceResponse<PagedResult<ApiAppSettingCategoryGetResponseModel>>>(ApiEndpoints.ApplicationSettingCategoryPagedList, pagedRequest).ConfigureAwait(false);

            if (!response.IsSuccessful)
            {
                return ToastError(response.Error);
            }

            return Ok(JsonDataTable(response.Result));
        }

        [HttpPost]
        [Authorize(Policy = KsPermissionPolicy.ManagementApplicationSettingCategoryCreate)]
        public async Task<IActionResult> PostAsync(ApplicationSettingCategoryPostModel model)
        {
            var response = await PostApiRequestAsync<ServiceResponse>(ApiEndpoints.ApplicationSettingCategoryBaseRoute, model).ConfigureAwait(false);

            if (!response.IsSuccessful)
            {
                return ToastError(response.Error);
            }

            return ToastSuccessForRedirect(_localize["CreateApplicationSettingCategorySuccess"], MvcEndpoints.ApplicationSettingCategoryBaseRoute);
        }

        [HttpPut]
        [Authorize(Policy = KsPermissionPolicy.ManagementApplicationSettingCategoryEdit)]
        public async Task<IActionResult> PutAsync(AppSettingCategoryPutViewModel model)
        {
            var response = await PutApiRequestAsync<ServiceResponse>(ApiEndpoints.ApplicationSettingCategoryBaseRoute, model).ConfigureAwait(false);

            if (!response.IsSuccessful)
            {
                return ToastError(response.Error);
            }

            return ToastSuccessForRedirect(_localize["UpdateApplicationSettingCategorySuccess"], MvcEndpoints.ApplicationSettingCategoryBaseRoute);
        }

        [HttpGet("search")]
        [Authorize(Policy = KsPermissionPolicy.ManagementApplicationSettingCategoryList)]
        public async Task<IActionResult> SearchAsync([FromQuery] ApplicationSettingCategorySearchRequest searchRequest)
        {
            var response = await GetApiRequestAsync<ServiceResponse<PagedResult<ApiAppSettingCategoryGetResponseModel>>>(ApiEndpoints.ApplicationSettingCategorySearch, searchRequest).ConfigureAwait(false);

            if (!response.IsSuccessful)
            {
                return ToastError(response.Error);
            }

            return Ok(JsonDataTable(response.Result));
        }

        private static ApplicationSettingCategorySearchRequest GetApplicationSettingCategorySearchRequest(DataTablesRequest requestModel)
        {
            var applicationSettingCategorySearchRequest = new ApplicationSettingCategorySearchRequest()
            {
                Name = requestModel.Search.Value,
                PageIndex = requestModel.Start / requestModel.Length,
                PageSize = requestModel.Length,
            };
            return applicationSettingCategorySearchRequest;
        }
    }
}

Presentation/KocSistem.CommunityEdition.Mvc/src/Views/ApplicationSettingCategory/Create.cshtml
@using KocSistem.CommunityEdition.Mvc.Helpers
@using KocSistem.OneFrame.I18N
@using KocSistem.CommunityEdition.Mvc.Controllers
@model KocSistem.CommunityEdition.Mvc.Models.ApplicationSettingCategory.ApplicationSettingCategoryViewModel
@inject HtmlMinSuffixHelper _htmlMinSuffixHelper
@inject IKsStringLocalizer<ApplicationSettingCategoryController> _localizer

@{
    ViewData["Title"] = _localizer["NewAppSettingCategory"];
}

<div class="modal fade" id="modalCreateApplicationSettingCategory" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered mw-650px">
        <div class="modal-content">
            <div class="modal-header">
                <h2>@_localizer["NewAppSettingCategory"]</h2>
                <div class="btn btn-sm btn-icon btn-active-color-primary" data-bs-dismiss="modal">
                    <span class="svg-icon svg-icon-1">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <rect opacity="0.5" x="6" y="17.3137" width="16" height="2" rx="1" transform="rotate(-45 6 17.3137)" fill="black" />
                            <rect x="7.41422" y="6" width="16" height="2" rx="1" transform="rotate(45 7.41422 6)" fill="black" />
                        </svg>
                    </span>
                </div>
            </div>
            <div class="modal-body scroll-y mx-5 mx-xl-15 my-7">
                <form class="form w-100" novalidate="novalidate" id="appSettingCategoryCreateForm" asp-controller="ApplicationSettingCategory" asp-action="Post" method="POST">
                    <div class="d-flex flex-column mb-8 fv-row">
                            <label asp-for="Name" class="d-flex align-items-center fs-6 fw-bold form-label mb-2 required"></label>
                            <input asp-for="Name" class="form-control form-control-solid" autocomplete="off" />
                    </div>
                    <div class="d-flex flex-column mb-8 fv-row">
                            <label asp-for="Description" class="d-flex align-items-center fs-6 fw-bold form-label mb-2"></label>
                            <input asp-for="Description" class="form-control form-control-solid" autocomplete="off" />
                    </div>
                    <div class="text-center pt-15">
                        <button type="reset" class="btn btn-light me-3" data-bs-dismiss="modal">@_localizer["Cancel"]</button>
                        <button type="button" id="appSettingCategoryCreateButton" class="btn btn-primary">
                            <span class="indicator-label">@_localizer["Submit"]</span>
                            <span class="indicator-progress">
                                @_localizer["PleaseWait"]...
                                <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
                            </span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="~/js/helpers/handlehelper@(_htmlMinSuffixHelper.MinSuffix).js"></script>
<script src="~/js/applicationSettingCategory/create@(_htmlMinSuffixHelper.MinSuffix).js"></script>

Presentation/KocSistem.CommunityEdition.Mvc/src/Views/ApplicationSettingCategory/Get.cshtml
@using KocSistem.OneFrame.I18N
@inject HtmlRtlSuffixHelper _htmlRtlSuffixHelper
@inject HtmlMinSuffixHelper _htmlMinSuffixHelper
@using KocSistem.CommunityEdition.Mvc.Helpers
@using KocSistem.CommunityEdition.Mvc.Controllers
@inject IKsStringLocalizer<ApplicationSettingCategoryController> _localizer
@{
    ViewData["Title"] = _localizer["AppSettingCategoryList"];
}

@section scripts
{
    <script src="~/metronic/assets/plugins/custom/datatables/datatables.bundle.js" type="text/javascript"></script>
    <script src="~/js/helpers/datatablehelper@(_htmlMinSuffixHelper.MinSuffix).js" type="text/javascript"></script>
    <script src="~/js/applicationSettingCategory/get@(_htmlMinSuffixHelper.MinSuffix).js" type="text/javascript"></script>
}

@section headerBegin
{
<link href="~/metronic/assets/plugins/custom/datatables/datatables.bundle@(_htmlRtlSuffixHelper.RtlFileSuffix).css" rel="stylesheet" type="text/css" />
}

<div class="row">
    <div class="card">
        <div class="card-header border-0 pt-6">
            <div class="card-title">
                <div class="d-flex align-items-center position-relative my-1">
                    <span class="svg-icon svg-icon-1 position-absolute ms-6">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="black" />
                            <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="black" />
                        </svg>
                    </span>
                    <input type="text" class="form-control form-control-solid w-250px ps-15 datatable-search" placeholder='@_localizer["DataTable_search"]' />
                </div>
            </div>
            <div class="card-toolbar">
                <div class="d-flex justify-content-end" data-kt-customer-table-toolbar="base">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalCreateApplicationSettingCategory"><em class="fa fa-plus"></em> @_localizer["NewAppSettingCategory"]</button>
                </div>
            </div>
        </div>
        <div class="card-body pt-0">
            <table class="table align-middle table-row-dashed fs-6 gy-5" id="table_appSettingCategory">
                <thead>
                    <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                        <th class="min-w-125px">@_localizer["Name"]</th>
                        <th class="min-w-125px">@_localizer["Description"]</th>
                        <th></th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

<partial name="Create.cshtml" />

<div id="editApplicationSettingCategory"></div>

Presentation/KocSistem.CommunityEdition.Mvc/src/Views/ApplicationSettingCategory/GetAppSettingCategoryInfo.cshtml
@using KocSistem.CommunityEdition.Mvc.Helpers
@using KocSistem.OneFrame.I18N
@using KocSistem.CommunityEdition.Mvc.Controllers
@model KocSistem.CommunityEdition.Mvc.Models.ApplicationSettingCategory.ApplicationSettingCategoryViewModel
@inject IKsStringLocalizer<ApplicationSettingCategoryController> _localizer
@inject HtmlMinSuffixHelper _htmlMinSuffixHelper
@inject HtmlRtlSuffixHelper _htmlRtlSuffixHelper

<div class="modal fade" id="modalEditApplicationSettingCategory" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered mw-650px">
        <div class="modal-content">
            <div class="modal-header">
                <h2>@_localizer["UpdateSettingCategory"]</h2>
                <div class="btn btn-sm btn-icon btn-active-color-primary" data-bs-dismiss="modal">
                    <span class="svg-icon svg-icon-1">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <rect opacity="0.5" x="6" y="17.3137" width="16" height="2" rx="1" transform="rotate(-45 6 17.3137)" fill="black" />
                            <rect x="7.41422" y="6" width="16" height="2" rx="1" transform="rotate(45 7.41422 6)" fill="black" />
                        </svg>
                    </span>
                </div>
            </div>
            <div class="modal-body scroll-y mx-5 mx-xl-15 my-7">
                <form class="form w-100" novalidate="novalidate" id="appSettingCategoryEditForm" asp-controller="ApplicationSettingCategory" asp-action="Put" method="PUT">
                    <input type="hidden" asp-for="Id"/>
                     <div class="d-flex flex-column mb-8 fv-row">
                            <label asp-for="Name" class="d-flex align-items-center fs-6 fw-bold form-label mb-2 required"></label>
                            <input asp-for="Name" class="form-control form-control-solid" autocomplete="off" />
                    </div>
                    <div class="d-flex flex-column mb-8 fv-row">
                            <label asp-for="Description" class="d-flex align-items-center fs-6 fw-bold form-label mb-2"></label>
                            <input asp-for="Description" class="form-control form-control-solid" autocomplete="off" />
                    </div>
                    <div class="text-center pt-15">
                        <button type="reset" class="btn btn-light me-3" data-bs-dismiss="modal">@_localizer["Cancel"]</button>
                        <button type="button" id="appSettingCategoryEditButton" class="btn btn-primary">
                            <span class="indicator-label">@_localizer["Submit"]</span>
                            <span class="indicator-progress">
                                @_localizer["PleaseWait"]...
                                <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
                            </span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="~/js/helpers/handlehelper@(_htmlMinSuffixHelper.MinSuffix).js"></script>
<script src="~/js/applicationSettingCategory/getappsettinginfo@(_htmlMinSuffixHelper.MinSuffix).js"></script>